### ISSUE TITLE
ImportError: cannot import name '_cv_app' from 'flask.globals'

### ISSUE THREAD

**Issue by jordaniscrosby** [Danangjoyoo/flask-http-middleware#3]
Got this error when upgrading to 0.2.0

running in pair with Flask==2.1.2

had to downgrade to fix

**Comment by Danangjoyoo** [comment]
@jordaniscrosby  thanks for noticing, will update soon

**Comment by Danangjoyoo** [comment]
the fix already released can upgrade to version 0.2.1. Its been tested and works well.

**Comment by Danangjoyoo** [comment]
will closed this issue as already solved

**Comment by jordaniscrosby** [comment]
thanks dude! love this wrapper you rock

**Comment by Danangjoyoo** [comment]
thanks! haha
