### ISSUE TITLE
Issue with Flask 3.0.0

### ISSUE THREAD

**Issue by Vishengel** [Danangjoyoo/flask-http-middleware#6]
Hi @Danangjoyoo,

When upgrading to Flask 3.0.0, the same error as reported in https://github.com/Danangjoyoo/flask-http-middleware/issues/2 and https://github.com/Danangjoyoo/flask-http-middleware/issues/5 pops up. 

For now, this can be fixed by downgrading to Flask 2.X.X, which is currently not a problem for me, but I thought I might give you a heads-up!

**Comment by Danangjoyoo** [comment]
Hi @Vishengel thanks for the heads up, I will check this and back to you soon!

**Comment by Danangjoyoo** [comment]
Hi @Vishengel I have updated the package and test it. Now it works as expected, please check it~

**Comment by Vishengel** [comment]
Hi @Danangjoyoo,

Indeed, the package now works with Flask 2.3.X and 3.X.X, thank you! 

However, please note that after updating your package to version 0.4.0, it no longer seems to work for older versions of Flask. I get the following error with Flask 2.2.2 and Werkzeug 2.2.2:
```Traceback (most recent call last):
  File "test.py", line 3, in <module>
    from flask_http_middleware import MiddlewareManager, BaseHTTPMiddleware
  File "INTERPRETER/lib/python3.10/site-packages/flask_http_middleware/__init__.py", line 1, in <module>
    from .manager import *
  File "/INTERPRETER/lib/python3.10/site-packages/flask_http_middleware/manager.py", line 9, in <module>
    flask_version = importlib.metadata.version("flask")
AttributeError: module 'importlib' has no attribute 'metadata'

Process finished with exit code 1

**Comment by Danangjoyoo** [comment]
Hi @Vishengel  I've just fixed this, kindly update to 0.4.1 🙇
